### PR TITLE
Bugfix/save listening position less frequently

### PR DESCRIPTION
**Pull request by jdempcy**
**What's this do?**
Update polling interval for saving listening position to 15 seconds (formerly 5 seconds).

**Why are we doing this? (w/ JIRA link if applicable)**
Reduce server load
https://www.notion.so/lyrasis/Android-Save-listening-position-less-frequently-ff7c6dc43caa492d98105a48e56d4c26

**How should this be tested? / Do these changes have associated tests?**
Open an audiobook, wait 15 seconds, confirm the bookmark animation appears on the bottom left of the screen. Exit the audiobook and open the same audiobook within the same account on a different device and confirm the bookmark was saved.

**Dependencies for merging? Releasing to production?**
Related to this issue: https://github.com/ThePalaceProject/android-core/pull/173 (not a dependency)

**Have you updated the changelog?**
Yes

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
Yes (@jdempcy)

### CODE REVIEW

**Comment by jdempcy** [comment]
If we want to get in the polling interval and README update, feel free to review and merge this and I can create a new PR.

Or, we can wait - my other task is to detect when the chapter has changed and save there.

I have a draft PR for android-core as well for updating on play, pause and stop:

https://github.com/ThePalaceProject/android-core/pull/173

**Comment by jdempcy** [comment]
I see also that the build has failed on the CI, so I'll have to investigate what caused that.

**Review by nunommts — CHANGES_REQUESTED** [review]
@jdempcy The changes look fine to me! Regarding your comments:

- I include `org.gradle.jvmargs=-Xmx2048m` on the gradle.properties file in order to solve the "out of memory" compiling issue. Then I avoid sending those changes when committing the changes;
- You need to set the building configuration [to this](https://user-images.githubusercontent.com/79104027/227888186-fa60658e-6470-4cf6-8bcf-6dabdf24b90b.png) and deploy it as a normal app. Then, you'll have a list of options to open the audiobook but the default ones are just fine for what you want, so you'll basically just have to run the app and move forward.

**Comment by nunommts** [comment]
@jdempcy I've noticed the ticket says the waiting time for the audiobook bookmarks should be of 15 seconds and not 5 minutes. Is there any reason why you set it with that value?

**Comment by jdempcy** [comment]
Thank you Nuno, I'll update it to 15 seconds! I set it to a much larger value as I had forgotten there was a value in the ticket, so I'll update it and we can wait and merge when everything is finished. My logic was, if it's already updating on every change, it shouldn't need to update so frequently. But I'll set it to 15 seconds, and I'll let you know when the other parts of the ticket are done.

**Comment by jdempcy** [comment]
I've updated the android-core ticket here with the refactored methods to de-duplicate code: https://github.com/ThePalaceProject/android-core/pull/173

Now all I have to do in android-core is verify that it's working, and get the failing test to pass - not sure why it is currently failing.

Then here in android-audiobook I'd like to figure out how to save the reading position to the server on chapter change. I have some good clues on how to do so thanks to your great guidance Nuno! So I will pursue that and follow up.

**Comment by nunommts** [comment]
@jdempcy Just a non too relevant note: I saw you mentioned the other PR on this PR's description but you could have done it under the *Dependencies for merging? Releasing to production?* section (even though it's not exactly a dependency) :)

Other than that, I saw your changes on the Changelog and you must have done something wrong because your entries went to the 9.0.2 version instead of the 9.0.1, which is the current version.

**Review by nunommts — APPROVED** [review]

**Comment by jdempcy** [comment]
No problem at all. Will do!

**Comment by jdempcy** [comment]
@nunommts I overwrote the gradle.properties with the updated version from main, and moved the changelog changes into the latest version (10.0.0). Let me know if there are any other changes to make, otherwise I think we are good to go!

**Review by nunommts — APPROVED** [review]
For me we're good to go too! You can merge this whenever you want.

**Pull request merged**
