### PR TITLE
Explicit bookmarks

### PR DESCRIPTION
**Pull request by io7m**
This deceptively large PR implements "explicit bookmarks". The deceptively large part is because I've moved the old Library Simplified example app into this repository in order to make development a bit easier in the future - previously, it was necessary to deploy the binaries to a local Maven repository and then use them in the demo app each time you wanted to test changes. For reviewing, please just ignore everything in the `org.librarysimplified.audiobook.demo` module.

This code adds a new "bookmark observer" class that is not actually exposed in the API but that is used internally to the ExoPlayer. Essentially, the bookmark observer subscribes to the player event stream and very conservatively publishes events that indicate that a new bookmark should now be created. The observer only listens to playback position updates, refuses to publish a bookmark event more frequently than every five seconds, and is careful about not publishing bookmark events too close to the start of a chapter. The assumption is that the bug involving player positions being lost is caused by the players publishing bad playback events (such as saying "You're now on chapter 0, position 0" upon closing the player).

Apps using the API need to be updated to _only_ create bookmarks when the underlying player publishes bookmark events. This will be the subject of another PR.

I've tested this with numerous open access books in the demo app, and it seems to work.

I've updated the group ID of the artifacts here to `org.thepalaceproject.audiobook` in preparation for publishing these to Maven Central.

### CODE REVIEW

**Comment by io7m** [comment]
This is PR 1 of 3, because there are separate PRs required for Findaway and for the app itself. Stay tuned...

**Review by ray-lee — APPROVED** [review]
This looks good!

**Comment by io7m** [comment]
I forgot to mention that the little bookmark icon should be considered optional by all means. I implemented it at first to get some visual feedback for the code, but it kind of grew on me. :smile:

**Comment by ray-lee** [comment]
Yes, I noticed that. I'm curious to see it in action!

**Pull request merged**
